### PR TITLE
Use current Mentat with better imports.

### PR DESCRIPTION
**Pull request by rnewman**
This doesn't build for me — Neon complains about not having x64 symbols. But it should be right.

Need to figure out how to call `new Date(timestamp)`.

### CODE REVIEW

**Comment by bgrins** [comment]
Thanks, I'll check it out locally.

> Need to figure out how to call new Date(timestamp)

I don't think neon has a date type implemented: https://docs.neon-bindings.com/neon/js/index.html.  So we'd either need to add that to neon or provide a wrapper to the Connection object that finds things that look like dates and convert them to actual dates when returning from query (https://github.com/bgrins/neon-mentat/blob/master/lib/connection.js#L3).  Initially returning it as a string or number is probably OK

**Comment by bgrins** [comment]
We will probably want to wrap up the native lib in a higher level api implemented in js at some point (to provide a way to transact and query without passing in an edn string), so modifying the return value on the way out is probably not a deal breaker

**Comment by rnewman** [comment]
> So we'd either need to add that to neon or provide a wrapper to the Connection object that finds things that look like dates and convert them to actual dates when returning from query

We already do return `DateTime<UTC>` values from the query, so they're distinct. Just need to figure out how to invoke the `Date` JS constructor, returning the result as a `JsObject` (with `.constructor == Date`), I think.

**Comment by bgrins** [comment]
Landed, thanks.  Just needed an extra commit to update the build script as neon-cli api changed in a minor version update and the npm dependency wasn't pinned

**Pull request merged**
